// dogan-consult-angular/src/app/components/language-switcher/language-switcher.component.ts
import { Component, signal, inject, HostListener } from '@angular/core';
import { LucideAngularModule } from 'lucide-angular';
import { APP_ICONS } from '../../shared/icons';
import { I18nService, Lang } from '../../shared/i18n.service';

@Component({
  selector: 'app-language-switcher',
  imports: [LucideAngularModule],
  template: `
    <div class="relative">
      <button
        (click)="isOpen.set(!isOpen())"
        class="flex items-center gap-1.5 px-2.5 py-1.5 sm:px-4 sm:py-2 rounded-lg hover:bg-gray-100 transition-colors border border-gray-200 sm:border-transparent"
      >
        <lucide-icon [img]="icons.Globe" [size]="14"></lucide-icon>
        <span class="text-xs sm:text-sm font-medium">{{ currentLang().short }}</span>
        <lucide-icon [img]="icons.ChevronRight" [size]="12" class="rotate-90 text-gray-400"></lucide-icon>
      </button>

      @if (isOpen()) {
        <div class="absolute top-full mt-2 bg-white rounded-lg shadow-xl border border-gray-200 py-1.5 min-w-[140px] z-50"
          [class.right-0]="true"
          [class.left-auto]="true"
        >
          @for (lang of languages; track lang.code) {
            <button
              (click)="selectLanguage(lang.code)"
              class="w-full px-3 py-2 hover:bg-gray-50 transition-colors flex items-center gap-2.5"
              [class.bg-blue-50]="i18n.lang() === lang.code"
              [class.text-blue-600]="i18n.lang() === lang.code"
              [class.font-medium]="i18n.lang() === lang.code"
              [class.text-gray-700]="i18n.lang() !== lang.code"
            >
              <span class="text-sm">{{ lang.flag }}</span>
              <span class="text-sm">{{ lang.name }}</span>
            </button>
          }
        </div>
      }
    </div>
  `,
})
export class LanguageSwitcherComponent {
  protected readonly icons = APP_ICONS;
  i18n = inject(I18nService);
  isOpen = signal(false);

  languages = [
    { code: 'ar' as Lang, name: 'العربية', short: 'ع', flag: '🇸🇦' },
    { code: 'en' as Lang, name: 'English', short: 'EN', flag: '🇬🇧' },
    { code: 'tr' as Lang, name: 'Türkçe', short: 'TR', flag: '🇹🇷' },
  ];

  currentLang() {
    return this.languages.find((l) => l.code === this.i18n.lang()) ?? this.languages[0];
  }

  selectLanguage(code: Lang): void {
    this.i18n.setLang(code);
    this.isOpen.set(false);
  }

  @HostListener('document:click', ['$event'])
  onDocumentClick(event: Event): void {
    if (this.isOpen()) {
      this.isOpen.set(false);
    }
  }
}

// ai-consult-react/src/components/LanguageSwitcher.tsx
import { useState, useEffect } from 'react';
import { Globe } from 'lucide-react';

export function LanguageSwitcher() {
  const [language, setLanguage] = useState<'ar' | 'en' | 'tr'>('ar');
  const [isOpen, setIsOpen] = useState(false);

  const languages = [
    { code: 'ar', name: 'العربية', flag: '🇸🇦' },
    { code: 'en', name: 'English', flag: '🇬🇧' },
    { code: 'tr', name: 'Türkçe', flag: '🇹🇷' }
  ];

  useEffect(() => {
    // Initialize from localStorage or default
    const savedLang = localStorage.getItem('language') as 'ar' | 'en' | 'tr';
    if (savedLang) {
      setLanguage(savedLang);
      updateDocument(savedLang);
    }
  }, []);

  const updateDocument = (code: 'ar' | 'en' | 'tr') => {
    if (code === 'ar') {
      document.documentElement.setAttribute('dir', 'rtl');
      document.documentElement.setAttribute('lang', 'ar');
    } else {
      document.documentElement.setAttribute('dir', 'ltr');
      document.documentElement.setAttribute('lang', code);
    }
  };

  const handleLanguageChange = (code: 'ar' | 'en' | 'tr') => {
    setLanguage(code);
    setIsOpen(false);
    localStorage.setItem('language', code);
    updateDocument(code);
  };

  return (
    <div className="relative">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-2 px-4 py-2 rounded-lg hover:bg-gray-100 transition-colors"
      >
        <Globe className="w-4 h-4" />
        <span className="text-sm">{languages.find(l => l.code === language)?.flag}</span>
        <span className="text-sm">{languages.find(l => l.code === language)?.name}</span>
      </button>

      {isOpen && (
        <div className="absolute top-full right-0 mt-2 bg-white rounded-lg shadow-lg border border-gray-200 py-2 min-w-[150px] z-50">
          {languages.map((lang) => (
            <button
              key={lang.code}
              onClick={() => handleLanguageChange(lang.code as 'ar' | 'en' | 'tr')}
              className={`w-full px-4 py-2 text-left hover:bg-gray-50 transition-colors flex items-center gap-2 ${
                language === lang.code ? 'bg-blue-50 text-blue-600' : 'text-gray-700'
              }`}
            >
              <span>{lang.flag}</span>
              <span className="text-sm">{lang.name}</span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
