// doganlab-angular/src/app/shared/components/footer/footer.component.ts
import { Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { I18nService } from '../../../core/i18n/i18n.service';
import { TranslatePipe } from '../../../core/i18n/translate.pipe';

@Component({
  selector: 'app-footer',
  imports: [RouterLink, TranslatePipe],
  template: `
    <footer class="bg-[#06060a] border-t border-white/5 text-gray-400">
      <div class="max-w-7xl mx-auto px-5 sm:px-6 lg:px-8 py-12 sm:py-16">
        <div class="grid grid-cols-2 md:grid-cols-4 gap-8 mb-10">
          <div class="col-span-2 md:col-span-1 space-y-4">
            <a routerLink="/" class="flex items-center gap-2">
              <div class="w-9 h-9 bg-gradient-to-br from-violet-600 to-purple-500 rounded-lg flex items-center justify-center">
                <span class="text-white font-bold text-xs">DL</span>
              </div>
              <span class="text-white font-semibold text-sm">{{ 'nav.brand' | translate }}</span>
            </a>
            <p class="text-gray-500 text-xs leading-relaxed">{{ 'footer.desc' | translate }}</p>
          </div>

          <div>
            <h4 class="text-white font-semibold mb-4 text-sm">{{ 'footer.products_title' | translate }}</h4>
            <ul class="space-y-2.5">
              <li><a routerLink="/products/shahin-ai" class="hover:text-violet-400 transition-colors text-xs">Shahin AI</a></li>
              <li><a routerLink="/products/dogan-ai" class="hover:text-violet-400 transition-colors text-xs">Dogan AI</a></li>
              <li><a routerLink="/products/saudi-business-gate" class="hover:text-violet-400 transition-colors text-xs">Saudi Business Gate</a></li>
              <li><a routerLink="/products/doganhub" class="hover:text-violet-400 transition-colors text-xs">DoganHub</a></li>
            </ul>
          </div>

          <div>
            <h4 class="text-white font-semibold mb-4 text-sm">{{ 'footer.network_title' | translate }}</h4>
            <ul class="space-y-2.5">
              <li><a href="https://doganconsult.com" target="_blank" rel="noopener noreferrer" class="hover:text-violet-400 transition-colors text-xs">{{ 'footer.group_dc' | translate }}</a></li>
              <li><a href="https://www.shahin-ai.com" target="_blank" rel="noopener noreferrer" class="hover:text-violet-400 transition-colors text-xs">{{ 'footer.group_shahin' | translate }}</a></li>
              <li><a href="https://www.saudibusinessgate.com" target="_blank" rel="noopener noreferrer" class="hover:text-violet-400 transition-colors text-xs">{{ 'footer.group_sbg' | translate }}</a></li>
            </ul>
          </div>

          <div>
            <h4 class="text-white font-semibold mb-4 text-sm">{{ 'footer.contact_title' | translate }}</h4>
            <ul class="space-y-2.5">
              <li class="text-xs">info&#64;doganconsult.com</li>
              <li class="text-xs" dir="ltr">+966 500 666 084</li>
              <li><a routerLink="/contact" class="hover:text-violet-400 transition-colors text-xs">{{ 'nav.contact' | translate }}</a></li>
            </ul>
          </div>
        </div>

        <div class="pt-6 border-t border-white/5 flex flex-col sm:flex-row justify-between items-center gap-3">
          <p class="text-gray-500 text-xs">{{ 'footer.copyright' | translate }}</p>
          <p class="text-gray-600 text-[10px]">One of Dogan Consult projects</p>
        </div>
      </div>
    </footer>
  `,
})
export class FooterComponent {
  i18n = inject(I18nService);
}

// ai-consult-react/src/components/dogan-lab/Footer.tsx
import { Mail, Phone, MapPin, Beaker, Linkedin, Twitter, LayoutGrid } from 'lucide-react';
import { Link } from 'react-router-dom';
import { COMPANY_INFO, ROUTES, DOMAINS } from '../shared/constants';

export function Footer() {
  return (
    <footer className="bg-black border-t border-gray-900 text-gray-300">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-12 mb-12">
          {/* Company Info */}
          <div className="space-y-4">
            <div className="flex items-center gap-2">
              <div className="w-10 h-10 bg-gradient-to-br from-purple-600 to-pink-600 rounded-lg flex items-center justify-center">
                <Beaker className="w-6 h-6 text-white" />
              </div>
              <div>
                <span className="text-white block font-bold">DoganLab</span>
                <span className="text-xs text-purple-400">Innovation Center</span>
              </div>
            </div>
            <p className="text-gray-500">
              The experimental arm of Dogan Consult, pushing the boundaries of what's possible in tech.
            </p>
            <div className="flex gap-4">
              <a href={COMPANY_INFO.social.linkedin} className="w-10 h-10 bg-gray-900 rounded-lg flex items-center justify-center hover:bg-purple-600 transition-colors">
                <Linkedin className="w-5 h-5" />
              </a>
              <a href={COMPANY_INFO.social.twitter} className="w-10 h-10 bg-gray-900 rounded-lg flex items-center justify-center hover:bg-purple-600 transition-colors">
                <Twitter className="w-5 h-5" />
              </a>
            </div>
          </div>

          {/* Research Areas */}
          <div>
            <h4 className="text-white mb-4">Research Areas | مجالات البحث</h4>
            <ul className="space-y-3">
              <li><a href="#" className="hover:text-purple-400 transition-colors">Generative AI</a></li>
              <li><a href="#" className="hover:text-purple-400 transition-colors">Computer Vision</a></li>
              <li><a href="#" className="hover:text-purple-400 transition-colors">Blockchain</a></li>
            </ul>
          </div>

          {/* Network */}
          <div>
            <h4 className="text-white mb-4">Network | الشبكة</h4>
            <ul className="space-y-3">
              <li>
                <Link to={ROUTES.doganHub} className="flex items-center gap-2 hover:text-purple-400 transition-colors">
                  <LayoutGrid className="w-3 h-3" />
                  <span>DoganHub ({DOMAINS.doganHub})</span>
                </Link>
              </li>
              <li>
                <Link to={ROUTES.shahinAI} className="hover:text-purple-400 transition-colors">
                  <span>Shahin AI ({DOMAINS.shahinAI})</span>
                </Link>
              </li>
              <li>
                <Link to={ROUTES.saudiBusinessGate} className="hover:text-purple-400 transition-colors">
                  <span>Saudi Business Gate</span>
                </Link>
              </li>
            </ul>
          </div>

          {/* Contact */}
          <div>
            <h4 className="text-white mb-4">Contact | اتصل بنا</h4>
            <ul className="space-y-3">
              <li className="flex items-start gap-3">
                <MapPin className="w-5 h-5 text-purple-400 flex-shrink-0 mt-1" />
                <span>{COMPANY_INFO.address}</span>
              </li>
              <li className="flex items-start gap-3">
                <Phone className="w-5 h-5 text-purple-400 flex-shrink-0 mt-1" />
                <a href={`tel:${COMPANY_INFO.phone}`} className="hover:text-purple-400 transition-colors">{COMPANY_INFO.phoneDisplay}</a>
              </li>
              <li className="flex items-start gap-3">
                <Mail className="w-5 h-5 text-purple-400 flex-shrink-0 mt-1" />
                <a href={`mailto:${COMPANY_INFO.email}`} className="hover:text-purple-400 transition-colors">{COMPANY_INFO.email}</a>
              </li>
            </ul>
          </div>
        </div>

        <div className="pt-8 border-t border-gray-900 text-center">
          <p className="text-gray-500">
            © 2024 DoganLab by Dogan Consult. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
}
